### ISSUE TITLE
valid PRs closed by develop -> main change

### ISSUE THREAD

**Issue by Code0x58** [pytest-dev/unittest2pytest#77] opened 2024-12-07 16:57 UTC
From looking at my inbox + the PR list, these were closed 1 hour ago
 - [x] #55 - nicoddemus reopened with #73
 - [ ] #47 - someone else's so I haven't touched it
 - [x] #48 - I reopened with #75
 - [x] #50 - I reopened with #76

It appears to have been caused by the removal of the `develop` branch

![image](https://github.com/user-attachments/assets/c3b27c15-139f-4189-921a-95520f923d25)

Nice to see some activity on this repo again

**Comment by nicoddemus** [comment] 2024-12-07 18:58
Indeed, that was the cause -- it was accidental as I thought GitHub would handle this correctly (re-targeting the branches in this case).

Thanks for reopening some of those, really appreciate it!

**Comment by nicoddemus** [comment] 2024-12-07 19:00
I think we can close this issue in particular, let me know if you want to keep it open for any reason.

**Closed by nicoddemus** 2024-12-07 19:00 UTC
